---
- name: Nasazeni Java aplikace na WildFly server
  hosts: your_server_group
  become: yes

  vars:
    java_home: "/opt/java"
    wildfly_home: "/opt/wildfly"
    wildfly_user: "wildfly"
    wildfly_group: "wildfly"
    wildfly_version: "25.0.1.Final"
    wildfly_url: "https://download.jboss.org/wildfly/{{ wildfly_version }}/wildfly-{{ wildfly_version }}.zip"
    app_url: "http://example.com/path/to/your/app.war"
    app_name: "your_app.war"

  tasks:
    - name: Instalace Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Pridani uzivatele pro WildFly
      user:
        name: "{{ wildfly_user }}"
        group: "{{ wildfly_group }}"
        system: yes
        state: present

    - name: Stazeni WildFly
      get_url:
        url: "{{ wildfly_url }}"
        dest: "/tmp/wildfly-{{ wildfly_version }}.zip"

    - name: Rozbaleni WildFly
      unarchive:
        src: "/tmp/wildfly-{{ wildfly_version }}.zip"
        dest: "/opt/"
        creates: "{{ wildfly_home }}/bin/standalone.sh"
        extra_opts: [--strip-components=1]
        owner: "{{ wildfly_user }}"
        group: "{{ wildfly_group }}"

    - name: Nasazeni aplikace
      get_url:
        url: "{{ app_url }}"
        dest: "{{ wildfly_home }}/standalone/deployments/{{ app_name }}"
        mode: '0755'
        owner: "{{ wildfly_user }}"
        group: "{{ wildfly_group }}"
      notify: Restart WildFly

  handlers:
    - name: Restart WildFly
      systemd:
        name: wildfly
        state: restarted