---
- name: Deploy and verify web application
  hosts: your_servers
  become: yes
  vars:
    app_directory: "/var/www/html/myapp"
    app_git_repo: "https://github.com/your_username/your_app_repo.git"
    app_port: 80

  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Clone application repository
      git:
        repo: "{{ app_git_repo }}"
        dest: "{{ app_directory }}"
        clone: yes
        update: yes

    - name: Install dependencies
      shell: |
        cd {{ app_directory }}
        npm install
      args:
        executable: /bin/bash

    - name: Start the application
      shell: |
        cd {{ app_directory }}
        nohup node app.js > /dev/null 2>&1 &
      args:
        executable: /bin/bash

    - name: Wait for application to start
      pause:
        seconds: 10

    - name: Check if web service is accessible
      uri:
        url: "http://{{ inventory_hostname }}:{{ app_port }}/"
        method: GET
        status_code: 200
      register: result

    - name: Output result
      debug:
        msg: "The web service is up and running!"
      when: result.status == 200

    - name: Fail if web service is not accessible
      fail:
        msg: "Failed to access the web service."
      when: result.status != 200